### ISSUE TITLE
Profile browser UX improvements

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#138]
## Todo

- [x] Add min/max width/height parameter to _profile info_ modal
- [x] Use consistent modal size for _profile info_ & _profile info edit_ modals
- [x] In _profile info edit_ modal description field is a required field, this may or may not be needed?
- [x] Add _save & close_ button next to the _save_ button in _profile info edit_ modal?

## Critical
- [x] Hitting Enter while the Title field is being edited in _profile info edit_ modal causes app to restart!

**Comment by bettyblack23** [comment]
Fix comments

- In _profile info edit_ modal description field is a required field, this may or may not be needed?
Description field is not required, because the profiles saved from _Session Profile_ has no description.

- Add _save & close_ button next to the _save_ button in profile info edit modal?
If clicking on the "Save" button and save is successful, the modal closes.

- Hitting Enter while the Title field is being edited in _profile info edit modal_ causes app to restart!
Hitting Enter doesn't cause anything.
