### ISSUE TITLE
Reset app setting cause app to quit on Linux (Appimage)

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#139]
when resetting app settings in Preferences, the persistent options are deleted, and the app is restarted simulating a clean start.

On Linux this possibly crashes the app.

Desired behavior would be the cause the app to restart! This worked fine before swapping the bundler!

## Todo 
- [ ] Fix Reset App Setting behavior
- [ ] Fix Refresh button behavior (when no module is connected) 
- [ ] Fix Restart button behavior (error notification)

**Comment by SukuWc** [comment]
This is on Linux (Appimage) only
