### ISSUE TITLE
Drag-n-drop actions update

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#180]
## ToDo
- [x] Action icon background color must fill full height
- [x] Action icon must also be draggable
- [x] Vertically center drag icon and action icon when action is open

## Would be nice
- [x] Hover effect on drag icon
