### ISSUE TITLE
Fix interaction tracking (selected option: Element)

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#518]
## Todo:
- [ ] Element tracking should stay on selected event but jump to interacted element.
- [ ] If event is not available on the newly selected element then just jump to button/encoder/potmeter based on element!
- [ ] Make selected interaction tracking mode persistent via $appSettings.persistent

### Interaction tracking jumps to the triggered Event instead of last opened Event, even when it is set to 'Element'. 1.2.46

Interaction tracking jumps to the triggered Event instead of last opened Event, even when it is set to 'Element'.

E.g. Turning pots when the UI is set to Init and tracking to Element should switch between the Inits of triggered Elements, but it keeps jumping to the pot Events instead as if IT was set to Event.

This issue is still present in 1.2.47.

**Comment by SukuWc** [comment]
Description updated with clear instructions
